--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/n2s/.config/wpg/wallpapers/Nier_Automata.jpg"

-- Special
background="#0c120d"
foreground="#fffff7"
cursor="#fffff7"

-- Colors
color0="#0c120d"
color1="#6d9b24"
color2="#6b8835"
color3="#5a81b0"
color4="#ce9735"
color5="#bd46a4"
color6="#c6e975"
color7="#ddddd0"
color8="#6cc078"
color9="#b2b881"
color10="#8ebd38"
color11="#ccce7a"
color12="#89be81"
color13="#b4d49d"
color14="#e0f4b0"
color15="#fffff7"
