# Shell variables
# Generated by 'wal'
wallpaper='/home/n2s/.config/wpg/wallpapers/Nier_Automata.jpg'

# Special
background='#0c120d'
foreground='#fffff7'
cursor='#fffff7'

# Colors
color0='#0c120d'
color1='#6d9b24'
color2='#6b8835'
color3='#5a81b0'
color4='#ce9735'
color5='#bd46a4'
color6='#c6e975'
color7='#ddddd0'
color8='#6cc078'
color9='#b2b881'
color10='#8ebd38'
color11='#ccce7a'
color12='#89be81'
color13='#b4d49d'
color14='#e0f4b0'
color15='#fffff7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
